import { useState } from 'react'

type Period = 'monthly' | 'quarterly'
type Range  = '3M' | '6M' | '1Y'

interface FinancialReportProps {
  onExport?: () => void
  onShare?: () => void
  onBack?: () => void
}

// Chart helpers — canonical pattern
const W = 330, H = 110, PAD = { t: 12, r: 10, b: 22, l: 10 }

function buildPath(pts: number[]) {
  const cw = W - PAD.l - PAD.r
  const ch = H - PAD.t - PAD.b
  const xs = pts.map((_, i) => PAD.l + (i / (pts.length - 1)) * cw)
  const ys = pts.map(v => PAD.t + (1 - v) * ch)
  let d = `M ${xs[0]} ${ys[0]}`
  for (let i = 1; i < xs.length; i++) {
    const cp = (xs[i] + xs[i - 1]) / 2
    d += ` C ${cp} ${ys[i - 1]}, ${cp} ${ys[i]}, ${xs[i]} ${ys[i]}`
  }
  const area = `${d} L ${xs[xs.length - 1]} ${H - PAD.b} L ${xs[0]} ${H - PAD.b} Z`
  return { d, area, xs, ys }
}

const MONTH_LABELS_3M  = ['Jun', 'Jul', 'Aug']
const MONTH_LABELS_6M  = ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug']
const MONTH_LABELS_1Y  = ['Sep', 'Nov', 'Jan', 'Mar', 'May', 'Jul', 'Sep']

const TREND_PTS: Record<Range, number[]> = {
  '3M': [0.72, 0.68, 0.74],
  '6M': [0.62, 0.68, 0.65, 0.72, 0.68, 0.74],
  '1Y': [0.50, 0.55, 0.60, 0.58, 0.65, 0.68, 0.74],
}
const MONTH_LABELS: Record<Range, string[]> = {
  '3M': MONTH_LABELS_3M,
  '6M': MONTH_LABELS_6M,
  '1Y': MONTH_LABELS_1Y,
}

const CATEGORIES: { label: string; amount: number; budget: number; color: string; pct: number }[] = []

const MONTHLY_INCOME = 0
const MONTHLY_SPEND  = CATEGORIES.reduce((s, c) => s + c.amount, 0)
const MONTHLY_SAVED  = MONTHLY_INCOME - MONTHLY_SPEND

export default function FinancialReport({ onExport, onShare, onBack }: FinancialReportProps) {
  const [period, setPeriod] = useState<Period>('monthly')
  const [range,  setRange]  = useState<Range>('3M')

  const multiplier = period === 'quarterly' ? 3 : 1
  const income = MONTHLY_INCOME * multiplier
  const spend  = MONTHLY_SPEND  * multiplier
  const saved  = MONTHLY_SAVED  * multiplier
  const savingsRate = Math.round((saved / income) * 100)

  const pts = TREND_PTS[range]
  const { d: linePath, area, xs, ys } = buildPath(pts)
  const hlIdx = pts.length - 1
  const hlX = xs[hlIdx], hlY = ys[hlIdx]
  const monthLabels = MONTH_LABELS[range]

  return (
    <div className="flex flex-col bg-bg" style={{ minHeight: 785 }}>
      {/* Header */}
      <div className="flex items-center gap-3 px-5 pt-4 pb-3 shrink-0">
        <button onClick={onBack} className="w-11 h-11 flex items-center justify-center rounded-full hover:bg-surface-hi transition-colors shrink-0">
          <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
            <path d="M12.5 15l-5-5 5-5" stroke="rgba(175,197,255,0.7)" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
        <div className="flex-1">
          <p className="font-display text-base font-extrabold text-gradient-primary tracking-tight">Financial Report</p>
          <p className="font-body text-[10px] text-text-muted">Generated by Fina · Aug 2026</p>
        </div>
        <button onClick={onShare} className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-surface-hi transition-colors">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M11 2l3 3-3 3M2 8v1a4 4 0 0 0 4 4h8" stroke="rgba(175,197,255,0.6)" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
        <button onClick={onExport} className="w-10 h-10 flex items-center justify-center rounded-full hover:bg-surface-hi transition-colors">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M3 10v3h10v-3M8 2v8M5.5 7.5L8 10l2.5-2.5" stroke="rgba(175,197,255,0.6)" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
      </div>

      {/* Period toggle */}
      <div className="px-5 pb-3 shrink-0">
        <div className="flex gap-2 p-1 rounded-[--radius-xl]" style={{ background: 'rgba(175,197,255,0.05)', border: '1px solid rgba(175,197,255,0.1)' }}>
          {(['monthly', 'quarterly'] as Period[]).map(p => (
            <button key={p} onClick={() => setPeriod(p)}
              className="flex-1 h-9 rounded-[--radius-lg] font-body text-xs font-semibold capitalize transition-all duration-[180ms]"
              style={{ background: period === p ? 'rgba(0,102,255,0.25)' : 'transparent', border: `1px solid ${period === p ? 'rgba(0,102,255,0.4)' : 'transparent'}`, color: period === p ? '#AFC5FF' : 'rgba(175,197,255,0.4)' }}>
              {p}
            </button>
          ))}
        </div>
      </div>

      <div className="flex-1 overflow-y-auto px-5 pb-8 flex flex-col gap-4" style={{ scrollbarWidth: 'none' }}>
        {/* Hero — income/spend/saved */}
        <div className="rounded-[--radius-2xl] overflow-hidden"
          style={{ background: 'linear-gradient(135deg, rgba(0,30,80,0.92), rgba(5,11,45,0.98))', border: '1px solid rgba(0,102,255,0.2)' }}>
          <div className="px-5 pt-4 pb-2 flex flex-col gap-1">
            <p className="font-body text-[10px] text-text-muted uppercase tracking-wider">{period === 'monthly' ? 'August 2026' : 'Q3 2026'}</p>
            <p className="font-display text-3xl font-extrabold tracking-tighter"
              style={{ background: 'var(--gradient-primary)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
              ${income.toLocaleString()}
            </p>
            <p className="font-body text-xs text-text-muted">total income</p>
          </div>
          <div className="flex px-5 py-3 gap-3">
            {[
              { label: 'Spent',   value: spend,  color: '#FF4D5A', sign: '-' },
              { label: 'Saved',   value: saved,  color: '#22C55E', sign: '+' },
              { label: 'Rate',    value: null,   color: '#3FE7FF', sign: '' },
            ].map(row => (
              <div key={row.label} className="flex-1 flex flex-col gap-0.5 py-2.5 px-3 rounded-[--radius-xl]"
                style={{ background: 'rgba(175,197,255,0.04)', border: '1px solid rgba(175,197,255,0.08)' }}>
                <p className="font-body text-[9px] text-text-muted uppercase tracking-wide">{row.label}</p>
                <p className="font-display text-base font-extrabold" style={{ color: row.color }}>
                  {row.value != null ? `${row.sign}$${row.value.toLocaleString()}` : `${savingsRate}%`}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Trend chart */}
        <div className="rounded-[--radius-2xl] overflow-hidden relative"
          style={{ background: 'linear-gradient(160deg, rgba(0,30,80,0.92) 0%, rgba(5,11,45,0.98) 100%)', border: '1px solid rgba(0,102,255,0.2)', boxShadow: '0 0 30px rgba(0,102,255,0.07)' }}>
          <div className="absolute inset-0 pointer-events-none" style={{ background: 'radial-gradient(ellipse 60% 40% at 50% 70%, rgba(63,231,255,0.05) 0%, transparent 70%)' }} />
          <div className="px-4 pt-4 pb-3 flex flex-col gap-3 relative">
            <div className="flex items-center justify-between">
              <p className="font-body text-xs font-semibold text-text-muted uppercase tracking-wider">Savings Trend</p>
              <div className="flex gap-1.5">
                {(['3M', '6M', '1Y'] as Range[]).map(r => (
                  <button key={r} onClick={() => setRange(r)}
                    className="h-6 px-2.5 rounded-full font-body text-[10px] font-semibold transition-all duration-[180ms]"
                    style={{ background: range === r ? 'rgba(0,102,255,0.25)' : 'rgba(175,197,255,0.06)', border: `1px solid ${range === r ? 'rgba(0,102,255,0.5)' : 'rgba(175,197,255,0.12)'}`, color: range === r ? '#AFC5FF' : 'rgba(175,197,255,0.4)' }}>
                    {r}
                  </button>
                ))}
              </div>
            </div>
            <div style={{ height: H }}>
              <svg width="100%" viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" style={{ overflow: 'visible' }}>
                <defs>
                  <linearGradient id="repGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="#22C55E" stopOpacity="0.18" />
                    <stop offset="100%" stopColor="#22C55E" stopOpacity="0" />
                  </linearGradient>
                  <filter id="repGlow"><feGaussianBlur stdDeviation="2.5" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter>
                </defs>
                <path d={area} fill="url(#repGrad)" />
                <path d={linePath} stroke="#22C55E" strokeWidth="2.5" strokeOpacity="0.25" fill="none" filter="url(#repGlow)" />
                <path d={linePath} stroke="#22C55E" strokeWidth="1.5" fill="none" strokeLinecap="round" />
                <line x1={hlX} y1={hlY} x2={hlX} y2={H - PAD.b} stroke="rgba(34,197,94,0.25)" strokeWidth="1" strokeDasharray="3 3" />
                <circle cx={hlX} cy={hlY} r="6" fill="rgba(34,197,94,0.15)" />
                <circle cx={hlX} cy={hlY} r="3.5" fill="#0b1120" stroke="#22C55E" strokeWidth="1.5" />
                <circle cx={hlX} cy={hlY} r="1.5" fill="#22C55E" />
                <g transform={`translate(${Math.min(hlX - 44, W - 88)}, ${Math.max(hlY - 32, PAD.t)})`}>
                  <rect rx="5" ry="5" width="82" height="24" fill="rgba(13,26,74,0.95)" stroke="rgba(34,197,94,0.4)" strokeWidth="0.75" />
                  <text x="7" y="10" fontFamily="monospace" fontSize="8" fill="#22C55E" fontWeight="600">+${saved.toLocaleString()}</text>
                  <text x="7" y="19" fontFamily="sans-serif" fontSize="7" fill="rgba(175,197,255,0.5)">{savingsRate}% saved</text>
                </g>
                {monthLabels.map((m, i) => (
                  <text key={m} x={xs[Math.round(i * (pts.length - 1) / (monthLabels.length - 1))]} y={H - 4} textAnchor="middle" fontFamily="sans-serif" fontSize="7" fill="rgba(175,197,255,0.25)">{m}</text>
                ))}
              </svg>
            </div>
          </div>
        </div>

        {/* Category breakdown */}
        <div>
          <p className="font-body text-xs font-semibold text-text-muted uppercase tracking-wider mb-3">Spending by Category</p>
          <div className="rounded-[--radius-2xl] overflow-hidden" style={{ border: '1px solid rgba(175,197,255,0.09)' }}>
            {CATEGORIES.map((cat, i) => {
              const over = cat.amount * multiplier > cat.budget * multiplier
              return (
                <div key={cat.label} className="px-4 py-3.5"
                  style={{ background: i % 2 === 0 ? 'rgba(175,197,255,0.02)' : 'transparent', borderTop: i > 0 ? '1px solid rgba(175,197,255,0.06)' : 'none' }}>
                  <div className="flex items-center gap-3 mb-1.5">
                    <div className="w-2.5 h-2.5 rounded-full shrink-0" style={{ background: cat.color, boxShadow: `0 0 5px ${cat.color}80` }} />
                    <p className="font-body text-sm font-semibold text-text flex-1">{cat.label}</p>
                    <p className="font-body text-sm font-bold" style={{ color: over ? '#FF4D5A' : cat.color }}>
                      ${(cat.amount * multiplier).toLocaleString()}
                    </p>
                    {over && (
                      <span className="h-4 px-1.5 rounded-full font-body text-[8px] font-bold flex items-center"
                        style={{ background: 'rgba(255,77,90,0.12)', color: '#FF4D5A', border: '1px solid rgba(255,77,90,0.25)' }}>
                        Over
                      </span>
                    )}
                  </div>
                  <div className="h-1.5 rounded-full overflow-hidden" style={{ background: 'rgba(175,197,255,0.08)' }}>
                    <div className="h-full rounded-full transition-all"
                      style={{ width: `${Math.min((cat.amount / cat.budget) * 100, 100)}%`, background: over ? '#FF4D5A' : cat.color, boxShadow: `0 0 4px ${over ? '#FF4D5A' : cat.color}60` }} />
                  </div>
                  <p className="font-body text-[9px] text-text-muted mt-1">{cat.pct}% of spending · budget ${(cat.budget * multiplier).toLocaleString()}</p>
                </div>
              )
            })}
          </div>
        </div>

        {/* Fina insight */}
        <div className="rounded-[--radius-2xl] px-4 py-3.5 flex items-start gap-3"
          style={{ background: 'rgba(0,102,255,0.06)', border: '1px solid rgba(0,102,255,0.2)' }}>
          <div className="w-8 h-8 rounded-xl flex items-center justify-center shrink-0"
            style={{ background: 'var(--gradient-primary)', boxShadow: '0 0 10px rgba(63,231,255,0.3)' }}>
            <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
              <circle cx="6.5" cy="4" r="2" fill="white" />
              <path d="M2 11c0-2.5 2-4.5 4.5-4.5S11 8.5 11 11" stroke="white" strokeWidth="1.1" strokeLinecap="round" fill="none" />
            </svg>
          </div>
          <div>
            <p className="font-body text-xs font-semibold text-text mb-0.5">Fina's Take</p>
            <p className="font-body text-[11px] text-text-muted leading-relaxed">
              Your savings rate improved to {savingsRate}% this {period === 'monthly' ? 'month' : 'quarter'}. Food & Dining is 3% over budget — worth watching next month. Everything else is on track.
            </p>
          </div>
        </div>

        {/* Export / Share row */}
        <div className="flex gap-3">
          <button onClick={onExport}
            className="flex-1 h-12 rounded-[--radius-2xl] font-body text-sm font-semibold flex items-center justify-center gap-2 transition-all active:scale-[0.98]"
            style={{ background: 'var(--gradient-primary)' }}>
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M2.5 9v3h9v-3M7 1v8M4.5 6.5L7 9l2.5-2.5" stroke="white" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" /></svg>
            Export PDF
          </button>
          <button onClick={onShare}
            className="flex-1 h-12 rounded-[--radius-2xl] font-body text-sm font-semibold flex items-center justify-center gap-2 transition-all active:scale-[0.98]"
            style={{ background: 'rgba(175,197,255,0.07)', border: '1px solid rgba(175,197,255,0.15)', color: '#AFC5FF' }}>
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M10 2l2.5 2.5L10 7M1.5 7v-.5A3.5 3.5 0 0 1 5 3h7.5" stroke="#AFC5FF" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round" /></svg>
            Share
          </button>
        </div>
      </div>
    </div>
  )
}
